version: '2'
services: 
    web:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8080:8080"
        env_file: ./api/.env
volumes:
    data-volume:
    node_modules:
    web-root:
        driver: local